config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :hotels do
  resources :reviews
end
get 'contacts/new', to: 'contacts#new', as: 'new_contact'
post 'contacts', to: 'contacts#create'
get 'contacts/:id', to: 'contacts#show', as: 'contact'
#get 'hotels', to: 'hotels#index'
#get 'hotels/:id', to: 'hotels#show', as: 'hotel'
root 'hotels#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/hotel.rb
class Hotel < ApplicationRecord
has_many :reviews
	mount_uploader :picture, PictureUploader
end

app/models/review.rb
class Review < ApplicationRecord
belongs_to :hotel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def index
  @contact = Contact.all
end
def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to contact_path(@contact)
    end
  end

  def show
  @contact = Contact.find(params[:id])
end


  def contact_params
    params.require(:contact).permit(:name, :mail, :content)
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
def index
  @hotels = Hotel.all
  @q = Hotel.ransack(params[:q])
  @hotels = @q.result(distinct: true)
end
 def show
  @hotel = Hotel.find(params[:id])
end
  def hotel_params
    params.require(:hotel).permit(:name, :description,:picture)
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	  def index
  	@hotel = Hotel.find(params[:hotel_id])
    @reviews = @hotel.reviews
  end
    def new
    @hotel = Hotel.find(params[:hotel_id])
    @review = @hotel.reviews.build
  end

  def create
    @hotel = Hotel.find(params[:hotel_id])
    @review = Review.new(review_params)
    if @review.save
      redirect_to hotel_reviews_path(@hotel)
    end
  end

  def review_params
    params.require(:review).permit(:name, :body,:rating, :hotel_id)
  end
    def show
    @hotel = Hotel.find(params[:hotel_id])
    @review = Review.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/contacts/new.html.erb
<h1>お問い合わせ</h1>

<%= form_with(model: @contact, local: true) do |form| %>
<!-- name -->
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_name %>
  </div>
<!-- description -->
  <div class="field">
    <%= form.label :mail %>
    <%= form.text_field :mail, id: :contact_mail %>
  </div>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :contact_content %>
  </div>

  <div class="actions">
    <%= form.submit '送信',class:"btn btn-info" %>
  </div>
<% end %>

app/views/contacts/show.html.erb
<h1>お問い合わせありがとうございました</h1>
<p><%= @contact.name %></p>
<p><%= @contact.mail %></p>
<p><%= @contact.content %></p>

app/views/hotels/index.html.erb
<%= search_form_for @q do |f| %>

  <%= f.label :name_cont %>
  <%= f.search_field :name_cont %>
<input type="submit" name="commit" value="Search" data-disable-with="Search" class="btn btn-info">
<% end %>
<h1>ホテルの一覧</h1>
<div class="container"> <!--左右に余白-->
		<div class="row"> <!--横並び-->
			<% @hotels.each do |hotel| %>
			<div class="col-md-3"> <!--12幅のうちの3-->
			 <div class="card">
    <img src=" <%= hotel.picture_url %>" class="card-img-top" alt="ホテルの写真">
    		  <div class="card-body">
      <h5 class="card-title"><%= hotel.name %></h5>
      <p class="card-text"><%= hotel.description %></p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    		  </div>
  			 </div>
	
			</div>
			<% end %>	
		</div>	
</div>

app/views/hotels/show.html.erb
<h1>ホテル詳細ページ</h1>
<p><%= @hotel.name %></p>
<p><%= @hotel.description %></p>
<%= image_tag(@hotel.picture_url, width: 600) if @hotel.picture.present? %>
<p><%= link_to 'レビューの一覧', hotel_reviews_path(@hotel) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
    <header>
      <div class="container">
  <nav class="navbar navbar-expand-sm navbar-light">
    <a class="navbar-brand font-italic" href="/" style="font-size: 30px"><u>Hotel Project</u></a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#menu">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div id="menu" class="collapse navbar-collapse d-flex justify-content-end">
      <ul class="navbar-nav">
        <li class="nav-item"><a href="/" class="nav-link">トップページ</a></li>
        <li class="nav-item"><a href="/contacts/new" class="nav-link">お問い合わせ</a></li>
      </ul>
    </div>
  </nav>  
</div>
    </header>
    <%= yield %>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<footer class="mt-5">
  <p class="text-center text-muted display-5 bg-light">Hotel Project</p>
</footer>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_with(model: [@hotel,@review], local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>
  <%= form.hidden_field :hotel_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/index.html.erb
<p>レビューの一覧</p>
<%= @reviews.each do |review| %>
  <p>
  <%= review.name %>
  <%= review.body %>
  <%= review.rating %>
  </p>
<% end %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form', review: @review %>

<%= link_to 'ホテルの詳細へ', hotel_path(@hotel) %>

app/views/reviews/show.html.erb
<p>
  <strong>name:</strong>
  <%= @review.name %>
</p>

<p>
  <strong>rating:</strong>
  <%= @review.rating %>
</p>

<p>
	<strong>body:</strong>
	<%= @review.body %>
<p>	

<p>
  <strong>hotel:</strong>
  <%= @review.hotel_id %>
</p>